# Generated by Django 3.0.6 on 2021-02-04 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=255)),
                ('cityname', models.CharField(max_length=255)),
                ('jobtitle', models.CharField(max_length=255)),
                ('mobno', models.CharField(max_length=12)),
                ('cnf_password', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company_Register', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
