# Generated by Django 3.0.6 on 2021-02-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_project_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_prize', models.CharField(max_length=255, null=True)),
                ('cash_prize_description', models.TextField(null=True)),
                ('letter_of_recommendation', models.CharField(max_length=255, null=True)),
                ('letter_of_recommendation_description', models.TextField(null=True)),
                ('internship_opportunity', models.CharField(max_length=255, null=True)),
                ('internship_opportunity_description', models.TextField(null=True)),
                ('team_lunch_with_ceo', models.CharField(max_length=255, null=True)),
                ('team_lunch_with_ceo_description', models.TextField(null=True)),
                ('job_opportunity', models.CharField(max_length=255, null=True)),
                ('job_opportunity_description', models.TextField(max_length=255, null=True)),
            ],
        ),
    ]
