# Generated by Django 3.0.6 on 2021-02-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=255)),
                ('deadline_date', models.CharField(max_length=255)),
                ('choose_template', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
