# Generated by Django 3.0.6 on 2021-02-05 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0005_project_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_prize', models.CharField(max_length=255, null=True)),
                ('cash_prize_description', models.TextField(null=True)),
                ('letter_of_recommendation', models.CharField(max_length=255, null=True)),
                ('letter_of_recommendation_description', models.TextField(null=True)),
                ('internship_opportunity', models.CharField(max_length=255, null=True)),
                ('internship_opportunity_description', models.TextField(null=True)),
                ('team_lunch_with_ceo', models.CharField(max_length=255, null=True)),
                ('team_lunch_with_ceo_description', models.TextField(null=True)),
                ('job_opportunity', models.CharField(max_length=255, null=True)),
                ('job_opportunity_description', models.TextField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Incentives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=140)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Detailss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=255)),
                ('deadline_date', models.CharField(max_length=255)),
                ('choose_template', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project_Detailss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=500)),
                ('nda', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project_Skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Incentive',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Project_Details',
        ),
        migrations.DeleteModel(
            name='Project_Skill',
        ),
    ]
