# Generated by Django 3.0.6 on 2021-02-05 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0006_auto_20210205_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_prize', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_prize_description', models.TextField(blank=True, null=True)),
                ('letter_of_recommendation', models.CharField(blank=True, max_length=255, null=True)),
                ('letter_of_recommendation_description', models.TextField(blank=True, null=True)),
                ('internship_opportunity', models.CharField(blank=True, max_length=255, null=True)),
                ('internship_opportunity_description', models.TextField(blank=True, null=True)),
                ('team_lunch_with_ceo', models.CharField(blank=True, max_length=255, null=True)),
                ('team_lunch_with_ceo_description', models.TextField(blank=True, null=True)),
                ('job_opportunity', models.CharField(blank=True, max_length=255, null=True)),
                ('job_opportunity_description', models.TextField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Incentives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Incentives',
        ),
    ]
