# Generated by Django 3.0.6 on 2021-02-05 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0007_auto_20210205_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=255)),
                ('deadline_date', models.CharField(max_length=255)),
                ('choose_template', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skill', models.CharField(max_length=500)),
                ('nda', models.CharField(max_length=255)),
                ('cash_prize', models.CharField(blank=True, default=None, max_length=140, null=True)),
                ('cash_prize_description', models.TextField(blank=True, default=None, null=True)),
                ('letter_of_recommendation', models.CharField(blank=True, default=None, max_length=140, null=True)),
                ('letter_of_recommendation_description', models.TextField(blank=True, default=None, null=True)),
                ('internsip_opportunity', models.CharField(blank=True, default=None, max_length=140, null=True)),
                ('internsip_opportunity_description', models.TextField(blank=True, default=None, null=True)),
                ('job_opportunity', models.CharField(blank=True, default=None, max_length=140, null=True)),
                ('job_opportunity_description', models.TextField(blank=True, default=None, null=True)),
                ('team_lunch_with_ceo', models.CharField(blank=True, default=None, max_length=140, null=True)),
                ('team_lunch_with_ceo_description', models.TextField(blank=True, default=None, null=True)),
                ('plan', models.CharField(blank=True, default=None, max_length=140, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Create_Project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
